name: CI

on:
  pull_request:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change as needed

      - name: Install dependencies
        run: npm install  # or your preferred package manager

      - name: Run tests
        run: npm test  # Adjust the command according to your test setup
